--15 BUSINESS PROBLEMS
1.COUNT THE NUMBER OF MOVIES VS TV SHOWS
SELECT
	TYPE,
	COUNT(*) AS TOTAL_CONTENT
FROM
	NETFLIX
GROUP BY
	TYPE
	
2.FIND THE MOST COMMON RATING FOR MOVIES AND TV SHOWS
SELECT
	TYPE,
	RATING
FROM
	(
		SELECT
			TYPE,
			RATING,
			RANK() OVER (
				PARTITION BY
					TYPE
				ORDER BY
					COUNT(*) DESC
			) AS RANKING
		FROM
			NETFLIX
		GROUP BY
			1,
			2
	) AS T1
WHERE
	RANKING = 1

3.LIST ALL MOVIES RELEASED IN A SPECIFIC YEAR(2020)
--2020
--MOVIES
SELECT
	*
FROM
	NETFLIX
WHERE
	TYPE = 'Movie'
	AND RELEASE_YEAR = 2020

4.FIND THE TOP 5 COUNTRIES WITH MOST CONTENT ON NETFLIX
--5

SELECT
	UNNEST(STRING_TO_ARRAY(REPLACE(TRIM(COUNTRY), ', ', ','), ',')) AS NEW_COUNTRY,
	COUNT(SHOW_ID) AS TOTAL_CONTENT
FROM
	NETFLIX
GROUP BY
	1
ORDER BY
	2 DESC
LIMIT
	5

5.IDENTIFY THE LONGEST MOVIE
--MOVIE
--DURATION


SELECT
	TITLE,
	SUBSTRING(DURATION, 1, POSITION('m' IN DURATION) -1)::INT DURATION
FROM
	NETFLIX
WHERE
	TYPE = 'Movie'
	AND DURATION IS NOT NULL
ORDER BY
	2 DESC LIMIT
	5

6.FIND CONTENT ADDED IN LAST 5 YEARS
--DATA ADDED
SELECT
	*
FROM
	NETFLIX
WHERE
	TO_DATE(DATE_ADDED, 'MONTH DD,YYYY') >= CURRENT_DATE - INTERVAL '5 YEARS'

7.FIND ALL MOVIES/TV SHOWS BY DIRECTOR CALLED 'RAJIV CHILAKA'

SELECT
TYPE,TITLE,DIRECTOR
FROM NETFLIX
WHERE DIRECTOR ILIKE'%Rajiv Chilaka%'

8.LIST ALL TV SHOWS WITH MORE THAN 5 SEASONS
SELECT
	*
FROM
	NETFLIX
WHERE
	TYPE = 'TV Show'
	AND SPLIT_PART(DURATION, ' ', 1)::NUMERIC > 5

9. COUNT THE NUMBER OF CONTENT ITEMS IN EACH GENRE
--LISTED_IN CONTENT

SELECT
UNNEST(STRING_TO_ARRAY(listed_in,',')) AS GENRE,
COUNT(show_id) AS COUNT_GENRE
FROM NETFLIX
GROUP BY 1
order by 2 desc

10. FIND EACH YEAR AND AVERAGE NUMBER OF CONTENT RELEASED BY INDIA ON NETFLIX.
RETURN TOP 5 YEAR WITH HIGHEST AVERAGE CONTENT RELEASE
--YEAR INDIA
--TOP 5 IN INDIA YEAR
--CONTENTS-DATE ADDED
SELECT
	EXTRACT(
		YEAR
		FROM
			TO_DATE(DATE_ADDED, 'Month DD,YYYY')
	) AS YEAR,
	COUNT(*) AS YEARLY_CONTENT,
	ROUND(
		COUNT(*)::NUMERIC / (
			SELECT
				COUNT(*)
			FROM
				NETFLIX
			WHERE
				COUNTRY = 'India'
		)::NUMERIC * 100,
		2
	) AS AVG_CONTENT
FROM
	NETFLIX
WHERE
	COUNTRY ='India'
GROUP BY
	1
ORDER BY
	YEARLY_CONTENT DESC
LIMIT
	5

11. SELECT ALL MOVIES THAT ARE DOCUMENTARIES
--MOVIES
--DOCUMENTARIES
SELECT
	*
FROM
	NETFLIX
WHERE
	TYPE = 'Movie'
	AND LISTED_IN ILIKE '%Documentaries%'

12.FIND ALL CONTENT WITHOUT A DIRECTOR
SELECT
	*
FROM
	NETFLIX
WHERE
	DIRECTOR IS NULL


13.FIND IN HOW MANY MOVIES ACTOR'SALMAN KHAN' APPEARED  IN LAST 10 YEARS.
--MOVIES
--SALMAN KHAN
--LAST 10 YEARS
SELECT
	*
FROM
	NETFLIX
WHERE
	CASTS ILIKE '%Salman Khan%'
	AND RELEASE_YEAR > EXTRACT(
		YEAR
		FROM
			CURRENT_DATE
	) -10

14.FIND THE TOP 10 ACTORS WHO HAVE APPEARED IN THE HIGHEST NUMBER OF MOVIES PRODUCED IN INDIA
--ACTORS TOP 10
--MOVIES
--COUNTRY INDIA
SELECT
	TRIM(UNNEST(STRING_TO_ARRAY(CASTS, ','))) AS ACTORS,
	COUNT(*) AS NO_OF_FILMS
FROM
	NETFLIX
WHERE
	COUNTRY ILIKE '%India%'
	AND TYPE = 'Movie'
GROUP BY
	1
ORDER BY
	2 DESC
LIMIT
	10

15.CATEGORIZE THE CONTENTS ON THE PRESENCE OF THE KEYWORDS 'KILL' AND 'VIOLENCE' IN THE DESCRIPTION 
FIELD.LABEL CONTENT CONTAINING THESE KEYWORDS AS 'BAD' AND ALL OTHER CONTENT AS 'GOOD'.COUNT HOW
MANY ITEMS FALL INTO EACH CATEGORY.
--KILL AND VIOLENCE
--GOOD AND BAD
--COUNT THEM
WITH
	NEW_TABLE AS (
		SELECT
			*,
			CASE
				WHEN DESCRIPTION ILIKE '%KILL%'
				OR DESCRIPTION ILIKE '%VIOLENCE%' THEN 'BAD_CONTENT'
				ELSE 'GOOD_CONTENT'
			END CATEGORY
		FROM
			NETFLIX
	)
SELECT
	CATEGORY,
	COUNT(*) AS TOTAL_CONTENT
FROM
	NEW_TABLE
GROUP BY
	1


